# UI Kit — Ganesh OS landing

A faithful, interactive recreation of the **Ganesh OS** landing experience, composed from this design system's own components. It is a *recreation of the existing product surface*, not a new design.

## Run it
Open `index.html`. It links the global `styles.css`, loads the compiled `_ds_bundle.js`, then mounts the page from the babel section files. (`_ds_bundle.js` is generated by the compiler — if the page is blank, the bundle hasn't been built yet.)

## What's here
- `index.html` — page shell: the fixed `.bgfx` background field (blurred orbs + masked grid), React/Babel + bundle loaders, and the `App` that assembles the sections with smooth-scroll nav.
- `Nav.jsx` — glassy sticky nav (brand glyph, tab links with active violet pill, Watch CTA).
- `Hero.jsx` — kicker → gradient headline → lede → CTA → the four-domain lanes panel (animates from "loud" to "balanced") → metric row. Uses `Badge`, `Button`, `DomainLane`, `StatTile`.
- `Sections.jsx` — `PersonaRouter` (clickable lens cards that show a route), `LifeGrid` (domain-accented `Card`s), `Governance` (the single-writer fence table + `CodeBlock` trust gate + `ChangeLogLine`s), `AgentCatalog` (left-accent agent cards grouped by concern), and `Footer`.

## Components composed
`Button`, `Badge`, `Card` / `CardEyebrow` / `CardOwner`, `DomainLane`, `StatTile`, `CodeBlock` (+ `Cg`/`Cc` spans), `ChangeLogLine` — all from `window.GaneshOSDesignSystem_462320`.

## Interactions
- Nav tabs scroll to and highlight their section.
- Hero lanes start dim/loud and settle to balanced after ~2.6s.
- Persona cards select on click and surface their reading route.
- Cards lift + glow on hover.

## Fidelity notes
Faithful to the source's structure and visual language; trimmed to representative content (e.g. 6 life cards and 3 agent groups rather than the full set). The animated 60-second "one day" demo and the deep tabbed deck from the original are out of scope for this kit.
